version: '3'

services:
    app:
        container_name: demo-shop
        build:
            dockerfile: ./docker/Dockerfile
            context: ./
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        ports:
            - "8085:80"
        depends_on:
            - mysql
        networks:
            - network

    # MySQL Database
    mysql:
        image: mysql:latest
        container_name: demo-shop-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: demo_shop_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_PASSWORD: null
        volumes:
            - 'mysql_data:/var/lib/mysql'
        ports:
            - "3308:3306"
        networks:
            - network

    # Redis Server
    redis:
        image: redis:latest
        container_name: demo-shop-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - network

volumes:
    mysql_data:

networks:
    network:
        driver: bridge
